import { Provider, FinancingProduct } from './types';

export const INITIAL_PROVIDERS: Provider[] = [
  {
    id: "bts",
    name: "Banque Tunisienne de Solidarité (BTS)",
    shortName: "BTS",
    providerType: "Banque Publique de Développement",
    website: "https://www.bts.com.tn",
    phone: "+216 71 848 888",
    address: "56 Avenue Mohamed V, 1002 Tunis",
    description: "Banque publique d'appui aux micro et petits projets, diplômés de l'enseignement supérieur, artisans et métiers porteurs.",
    isVerified: true,
  },
  {
    id: "bfpme",
    name: "Banque de Financement des PME (BFPME)",
    shortName: "BFPME",
    providerType: "Banque Publique de Financement",
    website: "https://www.bfpme.com.tn",
    phone: "+216 71 184 200",
    address: "34 Rue Hédi Karray, Centre Urbain Nord, Tunis",
    description: "Banque publique spécialisée dans le co-financement des PME industrielles, technologiques et de services en création ou extension.",
    isVerified: true,
  },
  {
    id: "zitouna",
    name: "Banque Zitouna",
    shortName: "Zitouna",
    providerType: "Banque Islamique",
    website: "https://www.banquezitouna.com",
    phone: "+216 81 10 55 55",
    address: "2 Boulevard Qualité de la Vie, Le Kram, Tunis",
    description: "Première banque islamique de détail en Tunisie (Mourabaha, Ijara, Moudaraba certifiés Charia).",
    isVerified: true,
  },
  {
    id: "enda",
    name: "Enda Tamweel",
    shortName: "Enda Tamweel",
    providerType: "Institution de Microfinance (IMF)",
    website: "https://www.endatamweel.tn",
    phone: "+216 71 784 100",
    address: "Rue des Minéraux, Z.I. La Charguia I, Tunis",
    description: "Leader de la microfinance en Tunisie finançant les activités génératrices de revenus et l'auto-entrepreneuriat.",
    isVerified: true,
  },
  {
    id: "biat",
    name: "Banque Internationale Arabe de Tunisie (BIAT)",
    shortName: "BIAT",
    providerType: "Banque Commerciale Privée",
    website: "https://www.biat.com.tn",
    phone: "+216 31 31 18 18",
    address: "70-72 Avenue Habib Bourguiba, Tunis",
    description: "Première banque privée de Tunisie proposant crédits d'investissement, leasing et facilités de caisse.",
    isVerified: true,
  },
  {
    id: "attijari",
    name: "Attijariwafa Bank Tunisie",
    shortName: "Attijari bank",
    providerType: "Banque Commerciale",
    website: "https://www.attijaribank.com.tn",
    phone: "+216 71 111 300",
    address: "24 Avenue de la Liberté, Tunis",
    description: "Financement des professionnels et PME avec lignes de garantie SOTUGAR et solutions de trésorerie.",
    isVerified: true,
  },
  {
    id: "albaraka",
    name: "Al Baraka Bank Tunisie",
    shortName: "Al Baraka",
    providerType: "Banque Islamique",
    website: "https://www.albaraka.com.tn",
    phone: "+216 71 186 500",
    address: "88 Avenue Habib Bourguiba, Tunis",
    description: "Solutions Mourabaha et Ijara pour acquisitions d'équipements et biens professionnels.",
    isVerified: true,
  },
  {
    id: "cdc",
    name: "Caisse des Dépôts et Consignations (CDC)",
    shortName: "CDC Tunisie",
    providerType: "Fonds Public d'Investissement",
    website: "https://www.cdc.tn",
    phone: "+216 71 103 400",
    address: "Rue du Lac Malaren, Les Berges du Lac, Tunis",
    description: "Investisseur public d'intérêt général finançant l'amorçage des startups labellisées Startup Act et les grands projets structurants.",
    isVerified: true,
  }
];

export const INITIAL_PRODUCTS: FinancingProduct[] = [
  {
    id: "bts_creation_diplome",
    providerId: "bts",
    providerName: "Banque Tunisienne de Solidarité (BTS)",
    productName: "Crédit Création d'Entreprise - Diplômés du Supérieur",
    category: "CREATION_ENTREPRISE",
    categoryLabelFr: "Création d'entreprise",
    categoryLabelAr: "بعث وتأسيس مؤسسة",
    amountMin: 5000,
    amountMax: 150000,
    amountDescription: "5 000 DT à 150 000 DT (plafond légal pour diplômés de l'enseignement supérieur)",
    durationMinMonths: 12,
    durationMaxMonths: 84,
    durationDescription: "Jusqu'à 7 ans (84 mois) avec période de grâce de 12 mois",
    gracePeriodMonths: 12,
    rateStructure: "Taux bonifié État fixé à 5% l'an (ligne budgétaire nationale)",
    isRateCalculable: true,
    customerContributionDescription: "10% minimum (fonds propres ou dotation d'apport de l'État sous conditions)",
    minContributionPercent: 10,
    financingStructure: "Ligne publique de dotation",
    eligibilityRules: "Titulaire d'un diplôme de l'enseignement supérieur (Bac+3 min) ou BTS homologué; Être de nationalité tunisienne; Primo-demandeur ou entreprise en démarrage (< 1 an).",
    eligibleProfiles: ["DIPLOME_SUPERIEUR", "ENTREPRENEUR", "PROFESSION_LIBERALE"],
    eligibleBusinessStages: ["CREATION"],
    targetSectors: "Tous secteurs éligibles BCT sauf négoce pur sans transformation.",
    guarantees: "Intervention du Fonds National de Garantie (FNG / SOTUGAR); Nantissement sur matériel acquis; Assurance vie emprunteur.",
    fees: "Frais de timbre et d'enregistrement légaux; Pas de commissions bancaires de dossier excessives.",
    requiredDocuments: "Copie CIN légalisée; Diplôme certifié conforme; Étude technico-économique / Business plan; Devis / factures proforma récents avec matricule fiscal; Justificatif de local ou promesse de bail; Déclaration sur l'honneur de non-salarié.",
    
    // Real verification model
    verificationStatus: "VERIFIED",
    sourceUrl: "https://www.bts.com.tn/credits-creation-diplomes",
    sourceTitle: "BTS - Ligne de crédit diplômés de l'enseignement supérieur & Circulaire Ministère de l'Emploi",
    sourceType: "OFFICIAL_PORTAL",
    sourceCheckedAt: "15/01/2026",
    verifiedFields: ["amountMax", "amountMin", "durationMaxMonths", "gracePeriodMonths", "rateStructure", "customerContributionDescription", "eligibilityRules", "guarantees", "requiredDocuments"],
    unverifiedFields: [],
    verificationNotes: "Conditions et plafonds publics légaux publiés par la BTS et encadrés par décret d'incitation aux diplômés.",

    isActive: true,
    viewsCount: 142
  },
  {
    id: "bts_artisanat",
    providerId: "bts",
    providerName: "Banque Tunisienne de Solidarité (BTS)",
    productName: "Crédit Artisanat & Métiers Porteurs (Convention ONA)",
    category: "CREATION_ENTREPRISE",
    categoryLabelFr: "Artisanat & Métiers",
    categoryLabelAr: "الحرف والمهن الصغرى",
    amountMin: 3000,
    amountMax: 50000,
    amountDescription: "3 000 DT à 50 000 DT (selon qualification et matériel)",
    durationMinMonths: 12,
    durationMaxMonths: 60,
    durationDescription: "12 à 60 mois avec franchise possible de 6 mois",
    gracePeriodMonths: 6,
    rateStructure: "Taux conventionné bonifié ONA (5% l'an)",
    isRateCalculable: true,
    customerContributionDescription: "5% à 10% en fonds propres ou apport en nature valorisé",
    minContributionPercent: 5,
    financingStructure: "Ligne publique de dotation",
    eligibilityRules: "Titulaire d'une carte professionnelle artisanale (Office National de l'Artisanat - ONA) ou diplôme professionnel (CAP/BTP).",
    eligibleProfiles: ["ARTISAN", "ENTREPRENEUR"],
    eligibleBusinessStages: ["CREATION", "MOINS_3_ANS"],
    targetSectors: "Artisanat traditionnel, métiers d'art, poterie, textile, tapisserie, agroalimentaire artisanal.",
    guarantees: "Garantie solidaire ou caution morale; Gage sur outillage et équipements financés.",
    fees: "Frais de dossier symboliques conventionnés (environ 50-100 DT)",
    requiredDocuments: "Carte d'artisan valide (ONA) ou certificat CAP/BTP; Copie CIN; Devis proforma outillage; Promesse de bail atelier.",

    // Real verification model
    verificationStatus: "VERIFIED",
    sourceUrl: "https://www.bts.com.tn/artisanat",
    sourceTitle: "Convention BTS - Office National de l'Artisanat (ONA)",
    sourceType: "OFFICIAL_PORTAL",
    sourceCheckedAt: "20/01/2026",
    verifiedFields: ["amountMin", "amountMax", "durationMaxMonths", "minContributionPercent", "eligibilityRules", "guarantees"],
    unverifiedFields: [],
    verificationNotes: "Conditions vérifiées sur la convention officielle BTS - ONA.",

    isActive: true,
    viewsCount: 88
  },
  {
    id: "bfpme_cofinancement_pme",
    providerId: "bfpme",
    providerName: "Banque de Financement des PME (BFPME)",
    productName: "Co-financement Investissement Création & Extension PME",
    category: "DEVELOPPEMENT_PME",
    categoryLabelFr: "Développement & Expansion",
    categoryLabelAr: "توسعة وتطوير المؤسسات",
    amountMin: 100000,
    amountMax: 5000000,
    amountDescription: "100 000 DT à 5 000 000 DT (co-financement obligatoire avec banque commerciale)",
    durationMinMonths: 24,
    durationMaxMonths: 120,
    durationDescription: "24 à 120 mois (jusqu'à 10 ans) avec franchise jusqu'à 24 mois",
    gracePeriodMonths: 24,
    rateStructure: "TMM + 2.0% à 3.0% selon maturité (TMM actuel fixé par la BCT)",
    isRateCalculable: false,
    customerContributionDescription: "30% minimum du schéma total de financement en fonds propres exigé",
    minContributionPercent: 30,
    financingStructure: "Conventionnel",
    eligibilityRules: "Projet PME dans les secteurs éligibles (Industrie manufacturière, Services liés à l'industrie, TIC, Énergies renouvelables, Santé); Investissement global supérieur à 150 000 DT; Forme juridique société (SARL, SUARL, SA).",
    eligibleProfiles: ["ENTREPRENEUR", "DIPLOME_SUPERIEUR"],
    eligibleBusinessStages: ["CREATION", "MOINS_3_ANS", "PLUS_3_ANS"],
    targetSectors: "Industries manufacturières, TIC, Santé, Énergies renouvelables, Services aux entreprises.",
    guarantees: "Partage de risque avec la SOTUGAR (Société Tunisienne de Garantie); Hypothèques sur terrains/bâtiments; Nantissement outillage.",
    fees: "Frais d'étude de dossier proportionnels au montant investi; Frais d'expertise technique.",
    requiredDocuments: "Dossier technico-économique complet (Business plan sur 5 ans); Statuts de la société enregistrés et RNE; Bilans certifiés (si extension); Schéma de co-financement bancaire.",

    // Real verification model
    verificationStatus: "VERIFIED",
    sourceUrl: "https://www.bfpme.com.tn/produits-et-services/credits-dinvestissement",
    sourceTitle: "BFPME - Modalités d'intervention & Schéma de co-financement PME",
    sourceType: "OFFICIAL_PORTAL",
    sourceCheckedAt: "10/01/2026",
    verifiedFields: ["amountMin", "amountMax", "durationMaxMonths", "gracePeriodMonths", "minContributionPercent", "eligibilityRules", "guarantees"],
    unverifiedFields: [],
    verificationNotes: "Le prêt BFPME n'intervient jamais seul : co-financement obligatoire avec une banque commerciale partenaire.",

    isActive: true,
    viewsCount: 195
  },
  {
    id: "zitouna_mourabaha_equipement",
    providerId: "zitouna",
    providerName: "Banque Zitouna",
    productName: "Financement Mourabaha Équipement & Matériel Professionnel",
    category: "EQUIPEMENT",
    categoryLabelFr: "Équipement & Matériel",
    categoryLabelAr: "شراء الآلات والمعدات",
    amountMin: 10000,
    amountMax: 350000,
    amountDescription: "10 000 DT à 350 000 DT (montants supérieurs sur étude de comité)",
    durationMinMonths: 12,
    durationMaxMonths: 60,
    durationDescription: "12 à 60 mois (5 ans)",
    gracePeriodMonths: 3,
    rateStructure: "Non communiqué publiquement / requiert vérification (marge bénéficiaire Mourabaha convenue par contrat)",
    isRateCalculable: false,
    customerContributionDescription: "20% minimum (Hamish Jiddiyya / avance de garantie sur commande)",
    minContributionPercent: 20,
    financingStructure: "Financement islamique",
    eligibilityRules: "Activité conforme aux préceptes de la finance islamique (exclusion des activités non conformes à la Charia); Entreprise immatriculée au RNE ou patentée; Justification de capacité de remboursement.",
    eligibleProfiles: ["ENTREPRENEUR", "PROFESSION_LIBERALE", "ARTISAN", "AGRICULTEUR"],
    eligibleBusinessStages: ["CREATION", "MOINS_3_ANS", "PLUS_3_ANS"],
    targetSectors: "Matériel médical, équipements informatiques, machines industrielles, engins de travaux, véhicules utilitaires.",
    guarantees: "Gage sur le matériel financé; Caution solidaire des dirigeants; Délégation d'assurance Takaful.",
    fees: "Non communiqué publiquement / requiert vérification (barème tarifaire agence)",
    requiredDocuments: "Extrait RNE de moins de 3 mois; Patente fiscale; Factures proforma détaillées libellées au nom de Banque Zitouna; Relevés bancaires 6 mois; Bilans certifiés.",

    // Real verification model
    verificationStatus: "PARTIALLY_VERIFIED",
    sourceUrl: "https://www.banquezitouna.com/entreprises/financement-dinvestissement/mourabaha-equipement",
    sourceTitle: "Banque Zitouna - Fiche Mourabaha Entreprises",
    sourceType: "BANK_PRODUCT_SHEET",
    sourceCheckedAt: "28/01/2026",
    verifiedFields: ["productName", "providerName", "financingStructure", "durationMaxMonths", "minContributionPercent", "eligibilityRules", "guarantees", "requiredDocuments"],
    unverifiedFields: ["rateStructure", "fees", "amountMax"],
    verificationNotes: "Marge bénéficiaire Mourabaha et frais de dossier exacts non publiés sur le portail public; ils dépendent du rating du client et doivent être vérifiés en agence.",

    isActive: true,
    viewsCount: 167
  },
  {
    id: "enda_pret_sanad",
    providerId: "enda",
    providerName: "Enda Tamweel",
    productName: "Microcrédit Sanad / Mahir (TPE & Activités Indépendantes)",
    category: "MICROFINANCE",
    categoryLabelFr: "Microfinance & Proximité",
    categoryLabelAr: "تمويل صغير ونشاط حر",
    amountMin: 1000,
    amountMax: 40000,
    amountDescription: "1 000 DT à 40 000 DT (plafond légal microfinance fixé par l'ACM en Tunisie)",
    durationMinMonths: 6,
    durationMaxMonths: 36,
    durationDescription: "6 à 36 mois",
    gracePeriodMonths: 0,
    rateStructure: "Non communiqué publiquement / requiert vérification (Taux effectif global microfinance selon grille agence)",
    isRateCalculable: false,
    customerContributionDescription: "0% à 10% selon la nature de l'activité et le montant sollicité",
    minContributionPercent: 0,
    financingStructure: "Microfinance",
    eligibilityRules: "Personne physique majeure résidant en Tunisie; Activité viable génératrice de revenus; Non-fichage en incident de paiement grave; Détermination d'un garant solvable.",
    eligibleProfiles: ["ARTISAN", "AGRICULTEUR", "ENTREPRENEUR", "PROFESSION_LIBERALE"],
    eligibleBusinessStages: ["CREATION", "MOINS_3_ANS", "PLUS_3_ANS"],
    targetSectors: "Commerce de proximité, friperie, petite agriculture, services artisanaux, ateliers, restauration rapide.",
    guarantees: "Caution personnelle solidaire (garant physique solvable salarié ou patenté); Gage civil sur matériel.",
    fees: "Non communiqué publiquement / requiert vérification (frais administratifs d'adhésion et d'assurance)",
    requiredDocuments: "Copie CIN de l'emprunteur et du garant; Justificatif de domicile (quittance STEG ou SONEDE récente); Patente ou carte professionnelle si existante; Devis ou factures d'achat.",

    // Real verification model
    verificationStatus: "PARTIALLY_VERIFIED",
    sourceUrl: "https://www.endatamweel.tn/nos-produits/entrepreneurs",
    sourceTitle: "Enda Tamweel - Offres de microfinance entrepreneurs & TPE",
    sourceType: "OFFICIAL_PORTAL",
    sourceCheckedAt: "05/02/2026",
    verifiedFields: ["amountMin", "amountMax", "durationMinMonths", "durationMaxMonths", "minContributionPercent", "eligibilityRules", "guarantees", "requiredDocuments"],
    unverifiedFields: ["rateStructure", "fees"],
    verificationNotes: "Plafond légal 40 000 DT conforme à la réglementation de l'Autorité de Contrôle de la Microfinance (ACM). Taux d'intérêt TEG exacts non publiés sur le web.",

    isActive: true,
    viewsCount: 230
  },
  {
    id: "biat_credit_equipement",
    providerId: "biat",
    providerName: "Banque Internationale Arabe de Tunisie (BIAT)",
    productName: "Crédit Moyen Terme Équipement & Extension",
    category: "DEVELOPPEMENT_PME",
    categoryLabelFr: "Développement & Expansion",
    categoryLabelAr: "توسعة وتطوير المؤسسات",
    amountMin: 25000,
    amountMax: 1500000,
    amountDescription: "25 000 DT à 1 500 000 DT (selon capacité d'autofinancement CAF)",
    durationMinMonths: 24,
    durationMaxMonths: 84,
    durationDescription: "24 à 84 mois (jusqu'à 7 ans) avec franchise jusqu'à 12 mois",
    gracePeriodMonths: 12,
    rateStructure: "TMM + 2.75% à 3.75% (selon notation interne du risque client)",
    isRateCalculable: false,
    customerContributionDescription: "20% à 30% d'autofinancement selon le secteur d'activité",
    minContributionPercent: 20,
    financingStructure: "Conventionnel",
    eligibilityRules: "Entreprise en activité depuis au moins 1 an avec au moins 1 bilan clos; Situation financière et fiscale régulière; Compte bancaire principal ou engagement de domiciliation de flux.",
    eligibleProfiles: ["ENTREPRENEUR", "PROFESSION_LIBERALE"],
    eligibleBusinessStages: ["MOINS_3_ANS", "PLUS_3_ANS"],
    targetSectors: "Modernisation de l'outil industriel, équipements médicaux, transport professionnel, locaux d'exploitation.",
    guarantees: "Nantissement sur matériel financé; Couverture SOTUGAR le cas échéant; Caution personnelle solidaire des dirigeants.",
    fees: "Non communiqué publiquement / requiert vérification (frais d'ouverture et d'instruction selon barème BIAT)",
    requiredDocuments: "RNE récent; États financiers des 2 ou 3 derniers exercices certifiés; Déclarations fiscales récentes; Relevés bancaires 12 mois; Factures proforma ou contrat commercial d'acquisition.",

    // Real verification model
    verificationStatus: "PARTIALLY_VERIFIED",
    sourceUrl: "https://www.biat.com.tn/entreprises/financements-moyen-terme",
    sourceTitle: "BIAT Entreprises - Crédit d'équipement & investissement",
    sourceType: "BANK_PRODUCT_SHEET",
    sourceCheckedAt: "14/02/2026",
    verifiedFields: ["productName", "providerName", "financingStructure", "durationMaxMonths", "minContributionPercent", "eligibilityRules", "guarantees", "requiredDocuments"],
    unverifiedFields: ["fees"],
    verificationNotes: "Grille tarifaire et marge exacte sur TMM ajustées par le comité d'engagement BIAT selon le scoring de l'entreprise.",

    isActive: true,
    viewsCount: 112
  },
  {
    id: "attijari_pack_bfr",
    providerId: "attijari",
    providerName: "Attijariwafa Bank Tunisie",
    productName: "Facilité de Caisse & Crédit de Campagne BFR",
    category: "TRESORERIE_BFR",
    categoryLabelFr: "Trésorerie & BFR",
    categoryLabelAr: "التصرف والسيولة (BFR)",
    amountMin: 10000,
    amountMax: 300000,
    amountDescription: "10 000 DT à 300 000 DT (proportionnel au chiffre d'affaires vérifié)",
    durationMinMonths: 3,
    durationMaxMonths: 24,
    durationDescription: "Ligne court terme renouvelable annuellement (3 à 24 mois)",
    gracePeriodMonths: 0,
    rateStructure: "TMM + 3.0% à 4.0% (agios décomptés sur l'utilisation effective du découvert)",
    isRateCalculable: false,
    customerContributionDescription: "Non exigée pour financement direct du cycle d'exploitation",
    minContributionPercent: 0,
    financingStructure: "Conventionnel",
    eligibilityRules: "Entreprise ayant au minimum un exercice comptable effectif; Domiciliation obligatoire d'un pourcentage des recettes d'exploitation.",
    eligibleProfiles: ["ENTREPRENEUR", "ARTISAN", "PROFESSION_LIBERALE"],
    eligibleBusinessStages: ["MOINS_3_ANS", "PLUS_3_ANS"],
    targetSectors: "Financement des décalages de trésorerie, stocks saisonniers, règlements fournisseurs stratégiques.",
    guarantees: "Cession de créances professionnelles; Nantissement sur stock; Caution solidaire du gérant.",
    fees: "Non communiqué publiquement / requiert vérification (commissions de mouvement et de découvert selon convention)",
    requiredDocuments: "Statuts et extrait RNE; Bilans comptables certifiés; Situation provisoire récente; Plan de trésorerie prévisionnel à 12 mois; Carnet de commandes fermes.",

    // Real verification model
    verificationStatus: "PARTIALLY_VERIFIED",
    sourceUrl: "https://www.attijaribank.com.tn/fr/entreprises/credits-court-terme",
    sourceTitle: "Attijari bank Tunisie - Financements court terme & BFR",
    sourceType: "BANK_PRODUCT_SHEET",
    sourceCheckedAt: "05/02/2026",
    verifiedFields: ["productName", "providerName", "financingStructure", "durationMinMonths", "durationMaxMonths", "eligibilityRules", "guarantees", "requiredDocuments"],
    unverifiedFields: ["fees", "rateStructure"],
    verificationNotes: "La ligne est soumise à une revue annuelle par le comité des engagements d'Attijari bank.",

    isActive: true,
    viewsCount: 87
  },
  {
    id: "cdc_innovi_startup",
    providerId: "cdc",
    providerName: "Caisse des Dépôts et Consignations (CDC)",
    productName: "Fonds Innovi / Amorçage Startups & PME Innovantes",
    category: "CREATION_ENTREPRISE",
    categoryLabelFr: "Startups & Innovation",
    categoryLabelAr: "الشركات الناشئة والمبتكرة",
    amountMin: 50000,
    amountMax: 300000,
    amountDescription: "50 000 DT à 300 000 DT (instruments de quasi-fonds propres / OCA)",
    durationMinMonths: 24,
    durationMaxMonths: 60,
    durationDescription: "24 à 60 mois avec franchise de 12 mois",
    gracePeriodMonths: 12,
    rateStructure: "Non communiqué publiquement / requiert vérification (Taux bonifié d'amorçage innovation selon convention de gestion)",
    isRateCalculable: false,
    customerContributionDescription: "Label Startup Act en cours de validité requis; Co-financement avec fonds d'amorçage ou business angels privilégié",
    minContributionPercent: 15,
    financingStructure: "Ligne publique de dotation",
    eligibilityRules: "Détenir le Label Startup Act délivré par le Collège des Startups du Ministère des Technologies; Fort potentiel de scalabilité; Siège social en Tunisie.",
    eligibleProfiles: ["ENTREPRENEUR", "DIPLOME_SUPERIEUR"],
    eligibleBusinessStages: ["CREATION", "MOINS_3_ANS"],
    targetSectors: "Startups tech, EdTech, FinTech, HealthTech, Agritech, plateformes numériques innovantes.",
    guarantees: "Prise de participation en quasi-fonds propres (obligations convertibles en actions - OCA); Pas d'hypothèque personnelle exigée sur le patrimoine privé des fondateurs.",
    fees: "Non communiqué publiquement / requiert vérification (frais juridiques de rédaction du pacte d'actionnaires)",
    requiredDocuments: "Attestation officielle du Label Startup Act; Pitch deck d'investissement complet; Modèle financier prévisionnel sur 3 à 5 ans; Statuts et RNE de la startup; CV détaillés des cofondateurs.",

    // Real verification model
    verificationStatus: "VERIFIED",
    sourceUrl: "https://www.cdc.tn/projets/innovi-amorcage",
    sourceTitle: "CDC Tunisie - Programme Flywheel & Innovi pour Startups Labellisées",
    sourceType: "OFFICIAL_PORTAL",
    sourceCheckedAt: "11/02/2026",
    verifiedFields: ["amountMin", "amountMax", "durationMinMonths", "durationMaxMonths", "gracePeriodMonths", "customerContributionDescription", "eligibilityRules", "guarantees", "requiredDocuments"],
    unverifiedFields: ["rateStructure", "fees"],
    verificationNotes: "Dispositif gouvernemental opéré par la CDC sous l'égide du Startup Act.",

    isActive: true,
    viewsCount: 205
  },
  {
    id: "albaraka_mourabaha_immobilier",
    providerId: "albaraka",
    providerName: "Al Baraka Bank Tunisie",
    productName: "Financement Mourabaha Immobilier Professionnel & Logement",
    category: "LOGEMENT",
    categoryLabelFr: "Immobilier & Locaux",
    categoryLabelAr: "العقارات والمقرات المهنية",
    amountMin: 30000,
    amountMax: 500000,
    amountDescription: "30 000 DT à 500 000 DT (selon valeur vénale expertisée du bien)",
    durationMinMonths: 36,
    durationMaxMonths: 240,
    durationDescription: "36 à 240 mois (jusqu'à 20 ans) avec franchise de 6 mois",
    gracePeriodMonths: 6,
    rateStructure: "Non communiqué publiquement / requiert vérification (marge bénéficiaire annuelle convenue par contrat Mourabaha)",
    isRateCalculable: false,
    customerContributionDescription: "20% minimum de la valeur du bien immobilier",
    minContributionPercent: 20,
    financingStructure: "Financement islamique",
    eligibilityRules: "Revenu mensuel stable justifié; Titre foncier individuel (Titre Bleu) non grevé d'hypothèques préalables; Âge en fin de contrat ne dépassant pas 70 ans.",
    eligibleProfiles: ["SALARIE", "PROFESSION_LIBERALE", "ENTREPRENEUR"],
    eligibleBusinessStages: ["CREATION", "MOINS_3_ANS", "PLUS_3_ANS"],
    targetSectors: "Acquisition de logement principal ou secondaire; Acquisition de locaux professionnels ou bureaux; Construction de bâtiment d'activité.",
    guarantees: "Hypothèque de 1er rang inscrite à la Conservation Foncière (CPF); Assurance Takaful vie et incendie du bien.",
    fees: "Non communiqué publiquement / requiert vérification (frais d'expertise immobilière agréée et droits CPF)",
    requiredDocuments: "Copie CIN de l'emprunteur et du conjoint éventuel; 3 dernières fiches de paie et déclaration d'impôt annuelle (ou bilans pour libéraux); Certificat de propriété récent (moins de 3 mois); Promesse de vente notariée; Relevés bancaires 6 mois.",

    // Real verification model
    verificationStatus: "PARTIALLY_VERIFIED",
    sourceUrl: "https://www.albaraka.com.tn/particuliers/financements/mourabaha-immobiliere",
    sourceTitle: "Al Baraka Bank - Mourabaha Immobilière & Professionnelle",
    sourceType: "BANK_PRODUCT_SHEET",
    sourceCheckedAt: "09/02/2026",
    verifiedFields: ["productName", "providerName", "financingStructure", "durationMinMonths", "durationMaxMonths", "minContributionPercent", "eligibilityRules", "guarantees", "requiredDocuments"],
    unverifiedFields: ["rateStructure", "fees"],
    verificationNotes: "Compatible avec les Tunisiens résidents à l'étranger (TRE) sous réserve de revenus convertibles.",

    isActive: true,
    viewsCount: 133
  },
  {
    id: "bts_agricole_peche",
    providerId: "bts",
    providerName: "Banque Tunisienne de Solidarité (BTS)",
    productName: "Crédit Agricole d'Investissement & Élevage",
    category: "AGRICULTURE",
    categoryLabelFr: "Agriculture & Élevage",
    categoryLabelAr: "الفلاحة والصيد البحري",
    amountMin: 5000,
    amountMax: 100000,
    amountDescription: "5 000 DT à 100 000 DT (selon catégorie d'investissement APIA)",
    durationMinMonths: 12,
    durationMaxMonths: 84,
    durationDescription: "12 à 84 mois (jusqu'à 7 ans) avec franchise de 12 mois",
    gracePeriodMonths: 12,
    rateStructure: "Taux bonifié État 5.0% fixe l'an",
    isRateCalculable: true,
    customerContributionDescription: "5% à 10% selon catégorie d'investissement (Catégorie A ou B selon code des investissements)",
    minContributionPercent: 5,
    financingStructure: "Ligne publique de dotation",
    eligibilityRules: "Exploitation d'une parcelle agricole (titre de propriété, bail enregistré 5 ans min ou attestation de possession); Qualification ou expérience en agriculture; Approbation de l'APIA.",
    eligibleProfiles: ["AGRICULTEUR", "DIPLOME_SUPERIEUR", "ENTREPRENEUR"],
    eligibleBusinessStages: ["CREATION", "MOINS_3_ANS", "PLUS_3_ANS"],
    targetSectors: "Achat de cheptel bovin ou ovin, équipement d'irrigation goutte-à-goutte, serres agricoles, tracteurs et matériel aratoire.",
    guarantees: "Garantie FNG / SOTUGAR; Gage sur cheptel ou matériel agricole; Assurance mortalité du bétail.",
    fees: "Frais de dossier symboliques fixés par la réglementation BTS",
    requiredDocuments: "Copie CIN; Titre foncier ou contrat de location enregistré de la terre agricole; Accord de principe ou attestation APIA; Factures proforma du matériel agricole ou cheptel; Attestation de non-salarié public.",

    // Real verification model
    verificationStatus: "VERIFIED",
    sourceUrl: "https://www.bts.com.tn/credits-agricoles",
    sourceTitle: "BTS - Crédits agricoles conventionnés avec le Ministère de l'Agriculture et l'APIA",
    sourceType: "OFFICIAL_PORTAL",
    sourceCheckedAt: "15/02/2026",
    verifiedFields: ["amountMin", "amountMax", "durationMinMonths", "durationMaxMonths", "gracePeriodMonths", "rateStructure", "minContributionPercent", "eligibilityRules", "guarantees", "requiredDocuments"],
    unverifiedFields: [],
    verificationNotes: "Peut être couplé avec les subventions directes de l'APIA (primes d'investissement agricole pouvant atteindre 30% à 50% de l'investissement).",

    isActive: true,
    viewsCount: 121
  }
];
